### ISSUE TITLE
Fix rounded corners on homepage

### ISSUE THREAD

**Issue by joswayski** [plutomi/plutomi#939]
Apparently this is bad because of reasons:

![CleanShot 2024-01-10 at 23 25 30@2x](https://github.com/plutomi/plutomi/assets/22891173/c66e009a-348c-4728-9a1c-55efb4ac6a7d)

And it should be like this instead (inner border radius being smaller than the outer:
![border](https://github.com/plutomi/plutomi/assets/22891173/3d302f2c-228f-438d-8a3f-617cbe74d283)

Should also be fixed here in the use case section:

![CleanShot 2024-01-10 at 23 26 15@2x](https://github.com/plutomi/plutomi/assets/22891173/8bc8d457-75fe-4f28-94b8-e9f4d5de54d9)

And on the copy email button on hover:
![CleanShot 2024-01-10 at 23 27 03@2x](https://github.com/plutomi/plutomi/assets/22891173/7f8c184b-88d9-45b4-a4a1-e47236950b2c)

**Comment by jlittlewood-scottlogic** [comment]
I'm happy to take a look at this issue if no one else is :)

**Comment by joswayski** [comment]
> I'm happy to take a look at this issue if no one else is :)

@jlittlewood-scottlogic sure go ahead! Let me know if you need help starting the web app :)

**Comment by jlittlewood-scottlogic** [comment]
https://github.com/plutomi/plutomi/pull/940

I have put up a PR fixing this issue if you want to take a look @joswayski

**Comment by joswayski** [comment]
Closed in #940 :) Thank you!
